<Project>
  <Choose>
    <When Condition="$(IsPackable) == true">
      <!-- Package License Information -->
      <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
      </PropertyGroup>
      <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)LICENSE" Pack="true" PackagePath="" />
      </ItemGroup>

      <!-- Source Link -->
      <ItemGroup>
        <SourceRoot Include="$(MSBuildThisFileDirectory)/" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401" PrivateAssets="All" />
      </ItemGroup>
      <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
      </PropertyGroup>
    </When>
  </Choose>
</Project>